spring:
  application:
    name: shn

server:
  port: 8090

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
